### ISSUE TITLE
Can you provide Street_Dataset?

### ISSUE THREAD

**Issue by ma3252788** [MenguChen/Federated_object_detection#1]
​Hello:
​    I am a doctoral student of Beijing University of Technology. I have seen your article "Real-World Image Datasets for Federated Learning", and I hope to reproduce your results, but I cannot find the Street_Dataset on GitHub. Would it be convenient for you to send me the download link of the dataset?
​
​Best,
​Chunjie

**Comment by maoweinuaa** [comment]
你得到这个数据集了吗？

**Comment by ma3252788** [comment]
> 你得到这个数据集了吗？

没有。。。

**Comment by maoweinuaa** [comment]
加个微信，保持联系，NASA1228

**Comment by maoweinuaa** [comment]
这个工程你跑起来了吗？

**Comment by AmingWu** [comment]
@maoweinuaa ，请问这个工程你跑起来了吗
